import { EmojiContent, Sender } from './types'
import { PackResult } from './bilibili/biliws'

export class MessageDanmu {
  sender: Sender
  content: string
  is_generated: boolean = false
  emoji_content: EmojiContent = null

  constructor(packet: PackResult) {
    this.sender.uid = 0
    this.sender.uname = packet.body.info[2][1]
    this.content = packet.body.info[1]
    if (packet.body.info[0][12] == 1) {
      this.emoji_content = packet.body.info[0][13]
    }
    // generated by gift or other kind of activities
    if (packet.body.info[0][9] > 0) {
      this.is_generated = true
    }
  }
}
